apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: loki-ruler-recording-rules
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: loki-ruler-recording-rules
    namespace: monitoring
    files:
      - sum_rate_tempo_logs.yml