apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-ruler-recording-rules
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: releases/medium/monitoring/recording-rules/loki
    repoURL: https://github.com/ishanjainn/loki-rules-using-gitops-medium.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true