apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: loki-ruler-alerting-rules
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: loki-ruler-alerting-rules
    namespace: monitoring
    files:
      - argocd-log-level.yml
