apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-ruler-alerting-rules
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: gitops/medium/monitoring/alerting-rules/loki
    repoURL: https://github.com/ishanjainn/medium.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
